### ISSUE TITLE
Just advice

### ISSUE THREAD

**Issue by lshaf** [erusev/base#1]
Hey dude,
maybe you can take a look for FuelPHP ORM. They have good example for your ORM :+1:

**Comment by erusev** [comment]
> hey have good example for your ORM

I'm not sure I understand.

**Comment by lshaf** [comment]
well, they have pretty good structure I think, and so easy to use.
even I say so I just compare FuelPHP ORM with Yii which using ActiveRecord ORM and yours.

**Comment by lshaf** [comment]
just look at their documentation. I think that will be your reference to build ORM sytax more easy :smile:

**Comment by erusev** [comment]
Thanks. 

Is it a separate package that can be used independently from the framework?

**Comment by lshaf** [comment]
yep but I've never try to use it independently.
I am really sure the ORM from fuelPHP is on separate packages.

for it you're welcome, and I just will wait for your best ORM, maybe you can make it more better than their ORM :smiley:

**Comment by erusev** [comment]
Thanks.

I appreciate the suggestion.
